### ISSUE TITLE
What is the project's licence?

### ISSUE THREAD

**Issue by Mayeu** [Xantios/dokku-cron#1]
Hello :wave:

Can you provide a licence for this project? I would like to use and build on it but without any licence this project falls under the normal copyright in my country.

You can use [Choose a licence](https://choosealicense.com/) to help you if you need.

Thanks 🙏

**Comment by Mayeu** [comment]
Note that I am happy to make a PR with the desired licence file as soon as you have chosen one 👍

**Comment by Xantios** [comment]
Hey,

Thanks for asking :) Do you have a preference for a license? 
I think MIT License would be a nice fit.

Feel free to make a PR

**Comment by Mayeu** [comment]
Fine for me, PR incoming :+1:
